name: CI

jobs:
  test:
    name: Run jest specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: test
  build:
    name: Transpile Typescript files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
